language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
- gem install bundler -v 2.0.1
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  repo: Zanark/Blog
  provider: pages
  local-dir: ./site
  target-branch: gh-pages
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_BLOG_TOKEN
  keep-history: true
  on:
    branch: master
